// Midnight Madness Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace AragornGameplayTags
{
	/* Input Tags */
	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);
	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);

	/* Player Tags */
	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);
	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);

	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);

	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe);
	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);

	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);

	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);
	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy);

	/* Enemy Tags */
	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);

	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);

	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Strafing);
	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_UnderAttack);

	/* Shared Tags */
	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);

	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);

	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);

	ARAGORN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead);
}